### ISSUE TITLE
asusctl not using ppd

### ISSUE THREAD

**Issue by flukejones** [mechakotik/rog-daemon#1]
Hi there, asusd is not using power-profiles-daemon for a while now. And it was using the /sysfs platform path directly up until I think 4.6.

power-profiles-daemon was a source of frustrations since it only did half the job it should have done, and I reverted back to managing throttle_thermal directly + adjusting the energy_performance_preference (configurable).

If you could update your notes please?

**Comment by mechakotik** [comment]
Hi, didn't know about it. If asusctl is not using PPD anymore, can you please update the manual and remove PPD dependency in your pacman repo?

**Comment by flukejones** [comment]
Was pretty sure I updated text but I'll check. There arch packaging isn't mine.
